version: "3.9"

services:
  backend:
    build:
      context: ..
      dockerfile: novelhub/backend/Dockerfile
    container_name: novelhub-backend
    env_file:
      - ./.env
    environment:
      JWT_SECRET: ${JWT_SECRET}
      SESSION_TTL_SECONDS: ${SESSION_TTL_SECONDS:-604800}
    ports:
      - "4000:4000"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:4000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - novelhub-net

  frontend:
    image: ${FRONTEND_IMAGE:-ghcr.io/your-gh-org/novelhub-frontend:latest}
    container_name: novelhub-frontend
    env_file:
      - ./.env
    environment:
      - VITE_API_BASE_URL=/api
    depends_on:
      backend:
        condition: service_healthy
    expose:
      - "8080"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - novelhub-net

  nginx:
    image: ${NGINX_IMAGE:-nginxinc/nginx-unprivileged:1.25-alpine}
    container_name: novelhub-nginx
    depends_on:
      frontend:
        condition: service_healthy
      backend:
        condition: service_healthy
    ports:
      - "${PORT:-8080}:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - novelhub-net

networks:
  novelhub-net:
    driver: bridge
